language: node_js
sudo: false
node_js:
  - 0.10
before_script:
  - npm install -g jasmine
  - npm install -g karma
  - npm install -g karma-chrome-launcher
  - npm install -g karma-firefox-launcher
  - npm install -g karma-jasmine
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - karma start karma.config.js --single-run
branches:
  only:
    - master
    - develop
    - /^deploy-.*$/
